# Generated by Django 5.1.6 on 2025-02-19 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='creator',
            new_name='seller',
        ),
    ]
