# Generated by Django 5.1.6 on 2025-02-22 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auction_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='ends_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 3, 24, 15, 8, 54, 535921, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='auction',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
